import { createFileRoute } from '@tanstack/react-router';
import { RequireAuth } from '@/components/RequireAuth';
import { useState } from 'react';
import { GlassCard } from '@/components/GlassCard';
import { TabBar } from '@/components/TabBar';
import { useTips } from '@/hooks/use-tips';
import { useSubscription } from '@/hooks/use-subscription';
import { UpgradePaywall } from '@/components/UpgradePaywall';
import { AdBanner } from '@/components/AdBanner';
import { FileText, Table, Download, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';

export const Route = createFileRoute('/tax')({
  component: () => <RequireAuth><TaxPage /></RequireAuth>,
  head: () => ({
    meta: [
      { title: 'TipTracker Pro — Tax Export' },
      { name: 'description', content: 'Export IRS-ready tax reports for your tip income.' },
    ],
  }),
});

function generateCSV(yearTips: Array<{ date: string; shift: string; cashAmount: number; cardAmount: number; amount: number; workplace: string; notes?: string }>) {
  const header = 'Date,Shift,Workplace,Cash Tips,Card Tips,Total,Notes';
  const rows = yearTips.map(t =>
    `${t.date},${t.shift},${t.workplace},$${t.cashAmount.toFixed(2)},$${t.cardAmount.toFixed(2)},$${t.amount.toFixed(2)},${t.notes || ''}`
  );
  const total = yearTips.reduce((s, t) => s + t.amount, 0);
  const cashTotal = yearTips.reduce((s, t) => s + t.cashAmount, 0);
  const cardTotal = yearTips.reduce((s, t) => s + t.cardAmount, 0);
  rows.push('');
  rows.push(`TOTAL,,,$${cashTotal.toFixed(2)},$${cardTotal.toFixed(2)},$${total.toFixed(2)},`);
  return [header, ...rows].join('\n');
}

async function generatePDF(yearTips: Array<{ date: string; shift: string; cashAmount: number; cardAmount: number; amount: number; workplace: string }>, year: number) {
  const { default: jsPDF } = await import('jspdf');
  await import('jspdf-autotable');

  const total = yearTips.reduce((s, t) => s + t.amount, 0);
  const cash = yearTips.reduce((s, t) => s + t.cashAmount, 0);
  const card = yearTips.reduce((s, t) => s + t.cardAmount, 0);
  const shifts = yearTips.length;

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();

  // Title
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('TipTracker Pro', 20, 25);

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100);
  doc.text(`${year} Annual Tax Report — IRS Form 4070 Reference`, 20, 33);

  // Summary boxes
  doc.setTextColor(0);
  const summaryY = 45;
  const boxW = (pageWidth - 50) / 2;

  const summaryItems = [
    { label: 'Total Reported Tips', value: `$${total.toFixed(2)}` },
    { label: 'Total Shifts', value: String(shifts) },
    { label: 'Cash Tips', value: `$${cash.toFixed(2)}` },
    { label: 'Card Tips', value: `$${card.toFixed(2)}` },
  ];

  summaryItems.forEach((item, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const x = 20 + col * (boxW + 10);
    const y = summaryY + row * 28;

    doc.setFillColor(245, 245, 245);
    doc.roundedRect(x, y, boxW, 24, 3, 3, 'F');

    doc.setFontSize(9);
    doc.setTextColor(120);
    doc.setFont('helvetica', 'normal');
    doc.text(item.label.toUpperCase(), x + 8, y + 10);

    doc.setFontSize(16);
    doc.setTextColor(0);
    doc.setFont('helvetica', 'bold');
    doc.text(item.value, x + 8, y + 20);
  });

  // Table
  const tableStartY = summaryY + 62;
  const tableData = yearTips.map(t => [
    t.date,
    t.shift,
    t.workplace,
    `$${t.cashAmount.toFixed(2)}`,
    `$${t.cardAmount.toFixed(2)}`,
    `$${t.amount.toFixed(2)}`,
  ]);

  (doc as any).autoTable({
    startY: tableStartY,
    head: [['Date', 'Shift', 'Workplace', 'Cash', 'Card', 'Total']],
    body: tableData,
    theme: 'plain',
    headStyles: {
      fillColor: [255, 255, 255],
      textColor: [100, 100, 100],
      fontStyle: 'bold',
      fontSize: 9,
      cellPadding: 4,
    },
    bodyStyles: {
      fontSize: 9,
      cellPadding: 4,
      textColor: [30, 30, 30],
    },
    alternateRowStyles: {
      fillColor: [250, 250, 250],
    },
    margin: { left: 20, right: 20 },
    didDrawPage: () => {
      // Footer on each page
      doc.setFontSize(8);
      doc.setTextColor(160);
      doc.setFont('helvetica', 'normal');
      const footerY = doc.internal.pageSize.getHeight() - 10;
      doc.text(
        `Generated by TipTracker Pro on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}. For personal record-keeping and tax preparation.`,
        20,
        footerY
      );
    },
  });

  doc.save(`TipTracker_${year}_Tax_Report.pdf`);
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function TaxPage() {
  const { yearTips } = useTips();
  const { isPro } = useSubscription();
  const [exported, setExported] = useState<'pdf' | 'csv' | null>(null);
  const year = new Date().getFullYear();
  const total = yearTips.reduce((s, t) => s + t.amount, 0);
  const cash = yearTips.reduce((s, t) => s + t.cashAmount, 0);
  const card = yearTips.reduce((s, t) => s + t.cardAmount, 0);
  const shifts = yearTips.length;

  const handleExportPDF = async () => {
    await generatePDF(yearTips, year);
    setExported('pdf');
    toast.success('Tax report downloaded!', { description: 'Your PDF tax report has been saved.' });
  };

  const handleExportCSV = () => {
    const csv = generateCSV(yearTips);
    downloadFile(csv, `TipTracker_${year}_Tips.csv`, 'text/csv');
    setExported('csv');
    toast.success('CSV exported!', { description: 'Your tip data has been downloaded.' });
  };

  return (
    <div className="min-h-screen max-w-[430px] mx-auto px-4 pt-12 pb-32">
      <div className="flex items-center gap-3 mb-5 animate-fade-in-up">
        <h1 className="text-[34px] font-bold text-foreground">Tax Export</h1>
        <span className="success-pill px-3 py-1 text-[13px] font-medium">IRS-Ready</span>
      </div>

      {/* Year summary */}
      <GlassCard className="mb-5 animate-fade-in-up stagger-1">
        <h2 className="text-[22px] font-semibold text-foreground">{year} Tax Summary</h2>
        <p className="text-[13px] text-muted-foreground mb-4">Jan 1 – Dec 31, {year}</p>
        <div className="h-px mb-4" style={{ background: 'rgba(255,255,255,0.12)' }} />
        {[
          { label: 'Total Reported Tips', value: `$${total.toFixed(2)}` },
          { label: 'Cash Tips', value: `$${cash.toFixed(2)}` },
          { label: 'Card Tips', value: `$${card.toFixed(2)}` },
          { label: 'Total Shifts', value: String(shifts) },
        ].map((row, i) => (
          <div key={row.label} className="flex items-center justify-between py-3" style={i < 3 ? { borderBottom: '0.5px solid rgba(255,255,255,0.12)' } : undefined}>
            <span className="text-[15px] text-muted-foreground">{row.label}</span>
            <span className="text-[15px] font-semibold text-foreground">{row.value}</span>
          </div>
        ))}
      </GlassCard>

      {/* Ad banner */}
      <div className="mb-5 animate-fade-in-up stagger-2">
        <AdBanner variant="inline" />
      </div>

      {/* Export format — paywalled */}
      <div className="mb-3 animate-fade-in-up stagger-2">
        <h3 className="text-[15px] font-semibold text-foreground mb-3">Export Format</h3>
      </div>

      {isPro ? (
        <GlassCard className="mb-3 !p-0 animate-fade-in-up stagger-2">
          <button onClick={handleExportPDF} className="w-full flex items-center gap-4 px-5 py-4" style={{ borderBottom: '0.5px solid rgba(255,255,255,0.12)' }}>
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'rgba(255,69,58,0.20)' }}>
              <FileText className="w-5 h-5" style={{ color: '#FF453A' }} />
            </div>
            <div className="flex-1 text-left">
              <p className="text-[15px] font-medium text-foreground">PDF Report</p>
              <p className="text-[13px] text-muted-foreground">Print-ready, IRS format</p>
            </div>
            {exported === 'pdf' ? <CheckCircle className="w-5 h-5" style={{ color: '#30D158' }} /> : <Download className="w-5 h-5 text-muted-foreground" />}
          </button>
          <button onClick={handleExportCSV} className="w-full flex items-center gap-4 px-5 py-4">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'rgba(48,209,88,0.20)' }}>
              <Table className="w-5 h-5" style={{ color: '#30D158' }} />
            </div>
            <div className="flex-1 text-left">
              <p className="text-[15px] font-medium text-foreground">CSV Spreadsheet</p>
              <p className="text-[13px] text-muted-foreground">For accountants</p>
            </div>
            {exported === 'csv' ? <CheckCircle className="w-5 h-5" style={{ color: '#30D158' }} /> : <Download className="w-5 h-5 text-muted-foreground" />}
          </button>
        </GlassCard>
      ) : (
        <div className="animate-fade-in-up stagger-2">
          <UpgradePaywall
            feature="Tax Export"
            description="Export your tip data as PDF or CSV reports. Upgrade to Pro to access tax exports."
          />
        </div>
      )}

      <TabBar />
    </div>
  );
}
