import { createFileRoute } from '@tanstack/react-router';
import { RequireAuth } from '@/components/RequireAuth';
import { useState } from 'react';
import { GlassCard } from '@/components/GlassCard';
import { TabBar } from '@/components/TabBar';
import { useTips } from '@/hooks/use-tips';
import { useSubscription } from '@/hooks/use-subscription';
import { UpgradePaywall } from '@/components/UpgradePaywall';
import { AdBanner } from '@/components/AdBanner';
import { FileText, Table, Download, CheckCircle } from 'lucide-react';
import { toast } from 'sonner';

export const Route = createFileRoute('/tax')({
  component: () => <RequireAuth><TaxPage /></RequireAuth>,
  head: () => ({
    meta: [
      { title: 'TipTracker Pro — Tax Export' },
      { name: 'description', content: 'Export IRS-ready tax reports for your tip income.' },
    ],
  }),
});

function generateCSV(yearTips: Array<{ date: string; shift: string; cashAmount: number; cardAmount: number; amount: number; workplace: string; notes?: string }>) {
  const header = 'Date,Shift,Workplace,Cash Tips,Card Tips,Total,Notes';
  const rows = yearTips.map(t =>
    `${t.date},${t.shift},${t.workplace},$${t.cashAmount.toFixed(2)},$${t.cardAmount.toFixed(2)},$${t.amount.toFixed(2)},${t.notes || ''}`
  );
  const total = yearTips.reduce((s, t) => s + t.amount, 0);
  const cashTotal = yearTips.reduce((s, t) => s + t.cashAmount, 0);
  const cardTotal = yearTips.reduce((s, t) => s + t.cardAmount, 0);
  rows.push('');
  rows.push(`TOTAL,,,$${cashTotal.toFixed(2)},$${cardTotal.toFixed(2)},$${total.toFixed(2)},`);
  return [header, ...rows].join('\n');
}

function generatePDFContent(yearTips: Array<{ date: string; shift: string; cashAmount: number; cardAmount: number; amount: number; workplace: string }>, year: number) {
  const total = yearTips.reduce((s, t) => s + t.amount, 0);
  const cash = yearTips.reduce((s, t) => s + t.cashAmount, 0);
  const card = yearTips.reduce((s, t) => s + t.cardAmount, 0);
  const shifts = yearTips.length;

  let html = `<!DOCTYPE html><html><head><meta charset="utf-8"><title>TipTracker Pro — ${year} Tax Report</title>
  <style>
    body { font-family: -apple-system, Helvetica, Arial, sans-serif; max-width: 800px; margin: 0 auto; padding: 40px; color: #1a1a1a; }
    h1 { font-size: 28px; margin-bottom: 4px; }
    .subtitle { color: #666; font-size: 14px; margin-bottom: 24px; }
    .summary { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-bottom: 32px; }
    .summary-item { padding: 16px; background: #f5f5f5; border-radius: 12px; }
    .summary-item .label { font-size: 12px; color: #666; text-transform: uppercase; letter-spacing: 0.5px; }
    .summary-item .value { font-size: 24px; font-weight: 600; margin-top: 4px; }
    table { width: 100%; border-collapse: collapse; font-size: 13px; }
    th { text-align: left; padding: 10px 12px; border-bottom: 2px solid #e0e0e0; font-weight: 600; color: #666; font-size: 11px; text-transform: uppercase; }
    td { padding: 10px 12px; border-bottom: 1px solid #f0f0f0; }
    .footer { margin-top: 32px; padding-top: 16px; border-top: 1px solid #e0e0e0; font-size: 11px; color: #999; }
  </style></head><body>
  <h1>TipTracker Pro</h1>
  <p class="subtitle">${year} Annual Tax Report — IRS Form 4070 Reference</p>
  <div class="summary">
    <div class="summary-item"><div class="label">Total Reported Tips</div><div class="value">$${total.toFixed(2)}</div></div>
    <div class="summary-item"><div class="label">Total Shifts</div><div class="value">${shifts}</div></div>
    <div class="summary-item"><div class="label">Cash Tips</div><div class="value">$${cash.toFixed(2)}</div></div>
    <div class="summary-item"><div class="label">Card Tips</div><div class="value">$${card.toFixed(2)}</div></div>
  </div>
  <table><thead><tr><th>Date</th><th>Shift</th><th>Workplace</th><th>Cash</th><th>Card</th><th>Total</th></tr></thead><tbody>`;

  yearTips.forEach(t => {
    html += `<tr><td>${t.date}</td><td>${t.shift}</td><td>${t.workplace}</td><td>$${t.cashAmount.toFixed(2)}</td><td>$${t.cardAmount.toFixed(2)}</td><td>$${t.amount.toFixed(2)}</td></tr>`;
  });

  html += `</tbody></table>
  <div class="footer">Generated by TipTracker Pro on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}. This report is for personal record-keeping and tax preparation purposes.</div>
  </body></html>`;
  return html;
}

function downloadFile(content: string, filename: string, type: string) {
  const blob = new Blob([content], { type });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = filename;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function TaxPage() {
  const { yearTips } = useTips();
  const { isPro } = useSubscription();
  const [exported, setExported] = useState<'pdf' | 'csv' | null>(null);
  const year = new Date().getFullYear();
  const total = yearTips.reduce((s, t) => s + t.amount, 0);
  const cash = yearTips.reduce((s, t) => s + t.cashAmount, 0);
  const card = yearTips.reduce((s, t) => s + t.cardAmount, 0);
  const shifts = yearTips.length;

  const handleExportPDF = () => {
    const html = generatePDFContent(yearTips, year);
    downloadFile(html, `TipTracker_${year}_Tax_Report.html`, 'text/html');
    setExported('pdf');
    toast.success('Tax report downloaded!', { description: 'Open the HTML file in your browser and print to PDF.' });
  };

  const handleExportCSV = () => {
    const csv = generateCSV(yearTips);
    downloadFile(csv, `TipTracker_${year}_Tips.csv`, 'text/csv');
    setExported('csv');
    toast.success('CSV exported!', { description: 'Your tip data has been downloaded.' });
  };

  return (
    <div className="min-h-screen max-w-[430px] mx-auto px-4 pt-12 pb-32">
      <div className="flex items-center gap-3 mb-5 animate-fade-in-up">
        <h1 className="text-[34px] font-bold text-foreground">Tax Export</h1>
        <span className="success-pill px-3 py-1 text-[13px] font-medium">IRS-Ready</span>
      </div>

      {/* Year summary */}
      <GlassCard className="mb-5 animate-fade-in-up stagger-1">
        <h2 className="text-[22px] font-semibold text-foreground">{year} Tax Summary</h2>
        <p className="text-[13px] text-muted-foreground mb-4">Jan 1 – Dec 31, {year}</p>
        <div className="h-px mb-4" style={{ background: 'rgba(255,255,255,0.12)' }} />
        {[
          { label: 'Total Reported Tips', value: `$${total.toFixed(2)}` },
          { label: 'Cash Tips', value: `$${cash.toFixed(2)}` },
          { label: 'Card Tips', value: `$${card.toFixed(2)}` },
          { label: 'Total Shifts', value: String(shifts) },
        ].map((row, i) => (
          <div key={row.label} className="flex items-center justify-between py-3" style={i < 3 ? { borderBottom: '0.5px solid rgba(255,255,255,0.12)' } : undefined}>
            <span className="text-[15px] text-muted-foreground">{row.label}</span>
            <span className="text-[15px] font-semibold text-foreground">{row.value}</span>
          </div>
        ))}
      </GlassCard>

      {/* Ad banner */}
      <div className="mb-5 animate-fade-in-up stagger-2">
        <AdBanner variant="inline" />
      </div>

      {/* Export format — paywalled */}
      <div className="mb-3 animate-fade-in-up stagger-2">
        <h3 className="text-[15px] font-semibold text-foreground mb-3">Export Format</h3>
      </div>

      {isPro ? (
        <GlassCard className="mb-3 !p-0 animate-fade-in-up stagger-2">
          <button onClick={handleExportPDF} className="w-full flex items-center gap-4 px-5 py-4" style={{ borderBottom: '0.5px solid rgba(255,255,255,0.12)' }}>
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'rgba(255,69,58,0.20)' }}>
              <FileText className="w-5 h-5" style={{ color: '#FF453A' }} />
            </div>
            <div className="flex-1 text-left">
              <p className="text-[15px] font-medium text-foreground">PDF Report</p>
              <p className="text-[13px] text-muted-foreground">Print-ready, IRS format</p>
            </div>
            {exported === 'pdf' ? <CheckCircle className="w-5 h-5" style={{ color: '#30D158' }} /> : <Download className="w-5 h-5 text-muted-foreground" />}
          </button>
          <button onClick={handleExportCSV} className="w-full flex items-center gap-4 px-5 py-4">
            <div className="w-10 h-10 rounded-xl flex items-center justify-center" style={{ background: 'rgba(48,209,88,0.20)' }}>
              <Table className="w-5 h-5" style={{ color: '#30D158' }} />
            </div>
            <div className="flex-1 text-left">
              <p className="text-[15px] font-medium text-foreground">CSV Spreadsheet</p>
              <p className="text-[13px] text-muted-foreground">For accountants</p>
            </div>
            {exported === 'csv' ? <CheckCircle className="w-5 h-5" style={{ color: '#30D158' }} /> : <Download className="w-5 h-5 text-muted-foreground" />}
          </button>
        </GlassCard>
      ) : (
        <div className="animate-fade-in-up stagger-2">
          <UpgradePaywall
            feature="Tax Export"
            description="Export your tip data as PDF or CSV reports. Upgrade to Pro to access tax exports."
          />
        </div>
      )}

      <TabBar />
    </div>
  );
}
